-- Bulk Insert 93 BNI Grow Members
-- Run this in Supabase SQL Editor

INSERT INTO members (name, business_field, company, joined_date, status) VALUES
('Achmad Faizal', 'Consulting (Other)', 'PT Abrisam Mitra Optima', CURRENT_DATE, 'active'),
('Adil Falah', 'Pest Control', 'Duta Artha Selaras', CURRENT_DATE, 'active'),
('Adrian Winata', 'Food Products', 'PT. Naturelle Inti Global', CURRENT_DATE, 'active'),
('Agnes Kristanty', 'Basic Metals', 'PT. Anugerah Kencana Mandiri Sentosa', CURRENT_DATE, 'active'),
('Albert Sebastian Rumawas', 'Paint Manufacture', 'PT Kebayoran Warna Prima', CURRENT_DATE, 'active'),
('Andi Asri', 'Transport & Shipping (Other)', 'ABC Express Cargo', CURRENT_DATE, 'active'),
('Andika Prabowo', 'Builder/General Contractor', 'SMART WINDOW', CURRENT_DATE, 'active'),
('Andre Chouw', 'IT & Networks', 'Ahacommerce.net', CURRENT_DATE, 'active'),
('Anna Meilanny', 'Sales Training/Coach', 'Korpora Trainindo Consultant PT', CURRENT_DATE, 'active'),
('Antony Jarto', 'Foreign Exchange', 'PT Global Mulia Valas - Money Changer', CURRENT_DATE, 'active'),
('Arif Setiawan', 'Health & Wellness Services', NULL, CURRENT_DATE, 'active'),
('Arifin Wibowo', 'Telecommunications (Other)', 'PT Cipta Teknik Utama', CURRENT_DATE, 'active'),
('Arvind Dhalomal Lalwani', 'Golf', 'Green Club Golf', CURRENT_DATE, 'active'),
('Azinul J Adrian', 'Food-Beverage Products', 'PT. AYUDIA KENCANA LARAS', CURRENT_DATE, 'active'),
('Bagus Putu Fabio', 'Human Resources', 'Ruang Manusia Meraki PT', CURRENT_DATE, 'active'),
('Ben Wirawan', 'Clothing & Accessories Retailer', 'PT. Maha Nagari Nusantara', CURRENT_DATE, 'active'),
('Benediktus Elvinto', 'Apparel', 'CHRONOX', CURRENT_DATE, 'active'),
('Bonaventura Adi Winarso', 'Media Services', 'Yudhaka Rekso Nusa', CURRENT_DATE, 'active'),
('Charles Antono', 'Nutritionist', 'Usana', CURRENT_DATE, 'active'),
('Davy Satria', 'Digital Marketing', 'Davy Satria Project', CURRENT_DATE, 'active'),
('Dedy Dahlan', 'Leadership & Training Development', 'Mitologi Inspira (PT Ansarmedia Edukreasi Semesta)', CURRENT_DATE, 'active'),
('Dihqon Nadaamist', 'Commercial Cleaning', 'Cleansheet', CURRENT_DATE, 'active'),
('Eka Sudjana', 'Digital Marketing', 'Hakka - Hoki Adi Karya', CURRENT_DATE, 'active'),
('Elisabeth Diany Pranata', 'Event Planner', 'PT Agape Nusantara Media', CURRENT_DATE, 'active'),
('Endang Kurniawan', 'Environmental Services', 'PT Indonesia Environment Consultant', CURRENT_DATE, 'active'),
('Erdy Suryadarma', 'Digital Imaging', 'Everidea Interactive', CURRENT_DATE, 'active'),
('Erly Salie', 'Tax Advisor', 'Lisanna Online Accounting and Tax Consultant', CURRENT_DATE, 'active'),
('Eva Shahra', 'Fuels', 'PT. Syntera Lampro Energy', CURRENT_DATE, 'active'),
('Febri Lovitasari', 'Cater', 'Vitasari Indonesia CV', CURRENT_DATE, 'active'),
('Felix Dharmaputra', 'Nutritionist', 'Prima Solusi Medikal, PT', CURRENT_DATE, 'active'),
('Grace Debby Suhaedy', 'Health Facility/Gym/Club', 'PT Grasia Cahaya Berkat', CURRENT_DATE, 'active'),
('Handy Johan Handoko', 'Building Materials', 'PT. Melia Optimus Indonesia', CURRENT_DATE, 'active'),
('Handy Widjaja', 'Automotive Expert', 'CV. Automobilindo Perkasa', CURRENT_DATE, 'active'),
('Hans Samuel Atmadjaja', 'Building Materials', 'PT Sutha Karya Steelindo (Sutha Karya Roofing)', CURRENT_DATE, 'active'),
('Harfil Husni', 'International Trading', 'Panca Makmur Baru, PT', CURRENT_DATE, 'active'),
('Hari Njotowidjojo', 'Architecture & Engineering (Other)', 'PT Hilios Power Quantum', CURRENT_DATE, 'active'),
('Hastomo Wijoyo', 'Tours/Tour Guide', 'CV. Panji Hannan Utama', CURRENT_DATE, 'active'),
('Hendy Gunawan', 'Electronics Retailer', 'GNS Teknik PT', CURRENT_DATE, 'active'),
('Herlambang Prayatno', 'Dry Cleaning/Laundry', 'PT. Anugrah Lima Semesta The Daily Wash', CURRENT_DATE, 'active'),
('Herwin Muchtar', 'Custom Apparel', 'CV Kincai Indah', CURRENT_DATE, 'active'),
('Ilham Kurniawan', 'IT & Networks', 'WIT.ID', CURRENT_DATE, 'active'),
('Iman Adhika Widjaya', 'Fire Protection', 'PT Abirama Ganendra Bagaspathi', CURRENT_DATE, 'active'),
('Irma Novita Andriiani', 'Intellectual Property Law', 'PT Rumah Paten Indonesia', CURRENT_DATE, 'active'),
('Jacky MA', 'Food & Beverage (Other)', 'PT. Tasma Ritelindo Jaya', CURRENT_DATE, 'active'),
('Jaksen Tamin', 'Promotional Products', 'Integra Multi Media Kreasi PT', CURRENT_DATE, 'active'),
('Jennyke Setiono', 'Lawyer', 'RJ Legal Consultants', CURRENT_DATE, 'active'),
('Jimmy Jimmy', 'Internet Service Provider', 'PT. Universal Broadband', CURRENT_DATE, 'active'),
('John Alan', 'Interior Architecture', 'Bauhaus Living', CURRENT_DATE, 'active'),
('Johny Gunawan', 'Financial Services', 'Koperasi Hartanah - Gajian Sekarang', CURRENT_DATE, 'active'),
('Ken Ratri Iswari', 'Employment Recruiter', 'PT.Geek Hunter International', CURRENT_DATE, 'active'),
('Kezia Hairun Nisa', 'Automotive Rental', 'PT Dave Indo Perkasa', CURRENT_DATE, 'active'),
('Kiyoko Tri Safitri', 'Commercial Loans', 'Loan Market Adam Malik', CURRENT_DATE, 'active'),
('Lie Alvin Yadiel Pamitro Arifin', 'Architect', 'Studio Pola Indonesia', CURRENT_DATE, 'active'),
('Lucky Priyatama Putra', 'Apparel', 'PT Hidup Ini Anugerah', CURRENT_DATE, 'active'),
('Lurus Ledyati', 'Manufacturing (Other)', 'PT Arkelindo Bara Sejahtera', CURRENT_DATE, 'active'),
('Mardjony Mardjony', 'Retail (Other)', 'Kopi Sidikalang Jaya', CURRENT_DATE, 'active'),
('Maria Soerjanti', 'Health Insurance', 'MSIG Life Insurance', CURRENT_DATE, 'active'),
('Maria Al Ghibtiyah', 'ERP Software', 'PT Beone Optima Solusi (Beone Solution)', CURRENT_DATE, 'active'),
('Mark P. Eliasaputra', 'Telecommunications Products/Services', 'Valdo International PT.', CURRENT_DATE, 'active'),
('Mas Agung Sachli', 'Computer Software', 'PT Integritas Makmur Mandiri', CURRENT_DATE, 'active'),
('Mayawati Nurhalim', 'Tours/Tour Guide', 'MyTrip, CV', CURRENT_DATE, 'active'),
('Mella Purwanaika', 'Event Venue/Room Rental', 'Jambuluwuk Hotels and Resorts', CURRENT_DATE, 'active'),
('Michael Rizal Koeswara', 'Photographer', 'Sinergi Cipta Optima PT', CURRENT_DATE, 'active'),
('Micky Hartono', 'Architectural Services', 'PT ICS Combotech', CURRENT_DATE, 'active'),
('Muhammad Rahmatullah', 'Health & Wellness Services', 'drmetzskincare', CURRENT_DATE, 'active'),
('Natalia Chintya Odang', 'Notary', 'Kantor Notaris Natalia Chintya Odang SH, M.Kn', CURRENT_DATE, 'active'),
('Nicholas Hira', 'Interior Architecture', 'Antik Decor', CURRENT_DATE, 'active'),
('Nida Issabela', 'Bedroom/Bath/Accessories', 'Substories Sukses Makmur', CURRENT_DATE, 'active'),
('Novi Liliana', 'Furniture Retailer', 'Subur Furniture', CURRENT_DATE, 'active'),
('Owen Fernando', 'Real Estate Development', 'Investaland Indonesia, PT', CURRENT_DATE, 'active'),
('Paul Iskandar', 'Event Planner', 'KreasiArt - PT.Multi Kreasi Mitrautama', CURRENT_DATE, 'active'),
('Prijono Arto Nugroho', 'Business Training/Coach', 'ActionCOACH Jakarta QQ', CURRENT_DATE, 'active'),
('Riene Mahardiani', 'Textiles', 'Zee Coll', CURRENT_DATE, 'active'),
('Rifqi Fuad', 'Real Estate Development', 'PT. Kultura Properties', CURRENT_DATE, 'active'),
('Ryan Kristo Muljono', 'Web Development', 'ToffeeDev', CURRENT_DATE, 'active'),
('Samuel Setiawan', 'Machinery & Equipment Manufacture', 'PT. Indoscale Sukses Mandiri', CURRENT_DATE, 'active'),
('Satrio Gunawan Ang', 'Property Management', 'Satrava', CURRENT_DATE, 'active'),
('Selviya Debora', 'Insurance Broker', 'Antara Intermediary Indonesia', CURRENT_DATE, 'active'),
('Setia Budi', 'Printing Services', 'Imperial Digital Printing', CURRENT_DATE, 'active'),
('Sissy Prima Laila', 'Art & Entertainment (Other)', 'PT Dewi Prima Kencana', CURRENT_DATE, 'active'),
('Soultan Nur Muhammad', 'Agriculture (Other)', 'CitrusHill Farm & Farming store', CURRENT_DATE, 'active'),
('Sri Wahyuni', 'Tea Distribution', 'PT Induk Prima Makmur (Tea N Tales)', CURRENT_DATE, 'active'),
('Stefan Joseph Kharismaputra', 'Glass', 'Royal Mugen', CURRENT_DATE, 'active'),
('Suntoro Suciatmaja', 'Feng Shui', 'Destiny Indonesia', CURRENT_DATE, 'active'),
('Surianto Iskandar', 'Packaging', 'PT Isuto Sukses Jaya', CURRENT_DATE, 'active'),
('Suryadi Suryadi', 'Entertainment Services', 'Personal Independent', CURRENT_DATE, 'active'),
('Tubagus M. Arry H.', 'Electronics Retailer', 'CAMZONE', CURRENT_DATE, 'active'),
('Verdy Santoso', 'Architectural Services', 'PT Venutama Jaya Sentosa', CURRENT_DATE, 'active'),
('Victor Oscar', 'Tours/Tour Guide', 'Blue Ocean Hosted Adventure', CURRENT_DATE, 'active'),
('Viktor Iwan', 'Advertising Agency', 'Doxadigital Indonesia, PT', CURRENT_DATE, 'active'),
('Wahyu Wibowo', 'Certified Public Accountant (CPA)', 'HLB Hadori Sugiarto Adi dan Rekan', CURRENT_DATE, 'active'),
('Widjanarka Budhihardjo', 'Baker', 'Barley Bakery', CURRENT_DATE, 'active'),
('Yogi Danugraha', 'Civil / structural engineer', 'PT. Wirasakti Nugratama', CURRENT_DATE, 'active'),
('Yohanes Memory Mangi Sa''pang', 'Civil Law', 'Mangi Sapang Attorneys at Law', CURRENT_DATE, 'active'),
('Yudhistira Harahap', 'Architectural Interior Design', 'PT. Yaph Design Group', CURRENT_DATE, 'active'),
('Yuli Prassetiowati', 'Food & Beverage (Other)', 'Kabira Food', CURRENT_DATE, 'active'),
('Yunus Suwanto Tjong', 'Building Materials', 'PT Aneka Juragan Material', CURRENT_DATE, 'active'),
('Zainal Arifin', 'Motorcycle Dealer', 'PT. Sinar Jaya Motor', CURRENT_DATE, 'active'),
('Zetra Kurniawan', 'Printing Services', 'PrintQuick Indonesia', CURRENT_DATE, 'active'),
('Zulfikar Rahman', 'Oil & Gas', 'PT. Energy Nusantara', CURRENT_DATE, 'active'),
('Zulhadi Bambang', 'Cattle Rancher', 'ZB Farm Indonesia', CURRENT_DATE, 'active');

-- Verify insert
SELECT COUNT(*) as total_members FROM members;
